In [1]:
import pandas as pd
import sklearn as sk
import numpy as np

In [2]:
titanic_df = pd.read_csv(
    "https://raw.githubusercontent.com/Animattronic/phd_materials/master/data_science/intro/data/titanic_train_data.csv",
    index_col=0,
    header=0)
titanic_df.head(2)

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   

             SibSp  Parch     Ticket     Fare Cabin Embarked  
PassengerId                                                   
1                1      0  A/5 21171   7.2500   NaN        S  
2                1      0   PC 17599  71.2833   C85        C

In [4]:
titanic_df.groupby('Sex').agg({'Age':np.mean})

Age
Sex              
female  27.915709
male    30.726645

In [8]:
from sklearn.datasets import load_boston
boston_data = load_boston()

In [10]:
print(boston_data.data)

[[  6.32000000e-03   1.80000000e+01   2.31000000e+00 ...,   1.53000000e+01
    3.96900000e+02   4.98000000e+00]
 [  2.73100000e-02   0.00000000e+00   7.07000000e+00 ...,   1.78000000e+01
    3.96900000e+02   9.14000000e+00]
 [  2.72900000e-02   0.00000000e+00   7.07000000e+00 ...,   1.78000000e+01
    3.92830000e+02   4.03000000e+00]
 ..., 
 [  6.07600000e-02   0.00000000e+00   1.19300000e+01 ...,   2.10000000e+01
    3.96900000e+02   5.64000000e+00]
 [  1.09590000e-01   0.00000000e+00   1.19300000e+01 ...,   2.10000000e+01
    3.93450000e+02   6.48000000e+00]
 [  4.74100000e-02   0.00000000e+00   1.19300000e+01 ...,   2.10000000e+01
    3.96900000e+02   7.88000000e+00]]


In [12]:
titanic_df.columns

Index(['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket',
       'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [27]:
pd.value_counts(titanic_df.Embarked)

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [95]:
titanic_df.head(5)

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S

In [28]:
columns_to_use = [
    'Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'
]
titanic_subset = titanic_df[columns_to_use]
titanic_subset.head(2)

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
PassengerId                                                                
1                   0       3    male  22.0      1      0   7.2500        S
2                   1       1  female  38.0      1      0  71.2833        C

In [37]:
titanic_subset_filled = titanic_subset.fillna(0)
titanic_subset_filled.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [38]:
titanic_subset_filled.head(2)

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
PassengerId                                                                
1                   0       3    male  22.0      1      0   7.2500        S
2                   1       1  female  38.0      1      0  71.2833        C

In [115]:
titanic_subset_filled.Pclass = titanic_subset_filled.Pclass.apply(lambda val: str(val))

In [116]:
titanic_binarized = pd.get_dummies(titanic_subset_filled)

In [117]:
titanic_binarized.head(3)

Survived   Age  SibSp  Parch     Fare  Pclass_1  Pclass_2  \
PassengerId                                                              
1                   0  22.0      1      0   7.2500         0         0   
2                   1  38.0      1      0  71.2833         1         0   
3                   1  26.0      0      0   7.9250         0         0   

             Pclass_3  Sex_female  Sex_male  Embarked_0  Embarked_C  \
PassengerId                                                           
1                   1           0         1           0           0   
2                   0           1         0           0           1   
3                   1           1         0           0           0   

             Embarked_Q  Embarked_S  
PassengerId                          
1                     0           1  
2                     0           0  
3                     0           1

In [118]:
titanic_subset.describe()

Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [32]:
titanic_subset.shape

(891, 8)

In [42]:
titanic_binarized.columns

Index(['Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Sex_female',
       'Sex_male', 'Embarked_0', 'Embarked_C', 'Embarked_Q', 'Embarked_S'],
      dtype='object')

In [119]:
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.tree import DecisionTreeClassifier

In [120]:
x = titanic_binarized.drop("Survived", axis=1)
x.head(1)

Age  SibSp  Parch  Fare  Pclass_1  Pclass_2  Pclass_3  \
PassengerId                                                           
1            22.0      1      0  7.25         0         0         1   

             Sex_female  Sex_male  Embarked_0  Embarked_C  Embarked_Q  \
PassengerId                                                             
1                     0         1           0           0           0   

             Embarked_S  
PassengerId              
1                     1

In [121]:
y = titanic_binarized.Survived

In [122]:
X_train, X_test, y_train, y_test = train_test_split(
    x, 
    y, 
    test_size=0.3)

In [123]:
from sklearn.tree import DecisionTreeClassifier

In [124]:
dt = DecisionTreeClassifier()

In [125]:
dt.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [69]:
from sklearn.metrics.classification import accuracy_score

In [126]:
predicted_y_test = dt.predict(X_test)

In [127]:
accuracy_score(y_true=y_test, y_pred=predicted_y_test)

0.78358208955223885

In [128]:
from sklearn.model_selection import cross_val_score

In [129]:
dt = DecisionTreeClassifier(max_depth=5)

In [130]:
dt.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=5,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [145]:
import sklearn.tree as tree
tree.export_graphviz(dt,out_file='tree.dot')

In [136]:
import pydot

In [144]:
from io import StringIO
dotfile = StringIO()
tree.export_graphviz(dt, out_file='tree.dot')
pydot.graph_from_dot_data(dotfile.getvalue()).write_png('treedot.png')

''

In [131]:
scores = cross_val_score(dt, X_train, y_train, cv=10)
scores

array([ 0.82539683,  0.76190476,  0.79365079,  0.82539683,  0.74193548,
        0.72580645,  0.77419355,  0.75806452,  0.79032258,  0.78688525])

In [105]:
list(zip(['a','b','c'], [1,2,3]))

[('a', 1), ('b', 2), ('c', 3)]

In [132]:
feature_importances = pd.DataFrame(list(zip(dt.feature_importances_, X_train.columns)))
feature_importances.columns = ['score', 'Feature']

In [133]:
feature_importances.sort_values(by='score', ascending=False)

score     Feature
7   0.580097  Sex_female
3   0.165292        Fare
6   0.106349    Pclass_3
0   0.076110         Age
1   0.033441       SibSp
2   0.029556       Parch
10  0.009155  Embarked_C
4   0.000000    Pclass_1
5   0.000000    Pclass_2
8   0.000000    Sex_male
9   0.000000  Embarked_0
11  0.000000  Embarked_Q
12  0.000000  Embarked_S

In [97]:
from sklearn.ensemble import GradientBoostingClassifier

In [99]:
xgb = GradientBoostingClassifier()

In [100]:
scores = cross_val_score(xgb, X_train, y_train, cv=10)
scores

array([ 0.76190476,  0.84126984,  0.92063492,  0.73015873,  0.79365079,
        0.77419355,  0.88709677,  0.82258065,  0.78688525,  0.81967213])

In [101]:
scores.mean()

0.81380473924101637

In [76]:
scores.std()

0.05928853139194442

In [34]:
177/891.

0.19865319865319866

In [31]:
titanic_subset.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [ ]:
titanic_subset.fillna()

In [16]:
from sklearn.model_selection import train_test_split

In [14]:
titanic_df_clean = titanic_df[['Pclass', 'Survived', 'Sex', 'SibSp', 'Parch', 'Fare']].fillna(0)
titanic_dummy = pd.get_dummies(titanic_df_clean)

In [15]:
titanic_dummy.head(4)

Pclass  Survived  SibSp  Parch     Fare  Sex_female  Sex_male
PassengerId                                                               
1                 3         0      1      0   7.2500           0         1
2                 1         1      1      0  71.2833           1         0
3                 3         1      0      0   7.9250           1         0
4                 1         1      1      0  53.1000           1         0

In [18]:
x, y = titanic_dummy.drop("Survived", axis=1), titanic_dummy.Survived

In [22]:
from sklearn.tree import DecisionTreeClassifier

In [23]:
dt = DecisionTreeClassifier()
dt.fit(x, y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [24]:
dt.feature_importances_

array([ 0.10643298,  0.06763795,  0.05625434,  0.38597018,  0.38370455,  0.        ])